const PROVINCES=['Adana','Adıyaman','Afyonkarahisar','Ağrı','Amasya','Ankara','Antalya','Artvin','Aydın','Balıkesir','Bilecik','Bingöl','Bitlis','Bolu','Burdur','Bursa','Çanakkale','Çankırı','Çorum','Denizli','Diyarbakır','Edirne','Elazığ','Erzincan','Erzurum','Eskişehir','Gaziantep','Giresun','Gümüşhane','Hakkâri','Hatay','Isparta','Mersin','İstanbul','İzmir','Kars','Kastamonu','Kayseri','Kırklareli','Kırşehir','Kocaeli','Konya','Kütahya','Malatya','Manisa','Kahramanmaraş','Mardin','Muğla','Muş','Nevşehir','Niğde','Ordu','Rize','Sakarya','Samsun','Siirt','Sinop','Sivas','Tekirdağ','Tokat','Trabzon','Tunceli','Şanlıurfa','Uşak','Van','Yozgat','Zonguldak','Aksaray','Bayburt','Karaman','Kırıkkale','Batman','Şırnak','Bartın','Ardahan','Iğdır','Yalova','Karabük','Kilis','Osmaniye','Düzce'];
const ICONS={'Türkçe':'📝','Temel Matematik':'√','Matematik':'∑','Fizik':'⚛','Kimya':'⚗','Biyoloji':'🧬','Tarih':'🏛','Coğrafya':'🌐','Felsefe':'🧠','Felsefe Grubu':'🧠','Din Kültürü ve Ahlak Bilgisi':'◈','Türk Dili ve Edebiyatı':'📚'};
const KEY='yks2027-arena-state-v1';let state=JSON.parse(localStorage.getItem(KEY)||'null')||{plan:'free',province:'',answered:0,correct:0,points:0,bySubject:{},seen:[]};if(!state.bySubject)state.bySubject={};if(!state.seen)state.seen=[];let session=[],responses=[],idx=0,locked=false,noteExam='ALL';
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateUI()}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='reports')renderReports();if(id==='zeus')renderCoach()}
function countdown(target,id){let d=target-new Date(),el=document.getElementById(id);if(d<=0){el.innerHTML='<div class="time" style="grid-column:1/-1"><b>Başladı</b></div>';return}let days=Math.floor(d/86400000);d%=86400000;let h=Math.floor(d/3600000);d%=3600000;let m=Math.floor(d/60000),s=Math.floor((d%60000)/1000);el.innerHTML=[['GÜN',days],['SAAT',h],['DAK',m],['SN',s]].map(x=>`<div class="time"><b>${String(x[1]).padStart(2,'0')}</b><span>${x[0]}</span></div>`).join('')}
function timers(){countdown(new Date('2027-06-19T10:15:00+03:00'),'tytTimer');countdown(new Date('2027-06-20T10:15:00+03:00'),'aytTimer')}
function rankModel(){if(!state.answered)return{tr:null,il:null,trTotal:1247386,ilTotal:0};let a=state.correct/state.answered,c=Math.min(state.answered/30,1),p=Math.min(state.points/300,1),perf=a*.6+c*.3+p*.1,percent=Math.min(.997,Math.max(.01,perf*perf*.997)),trTotal=1247386,tr=Math.max(1,Math.round(trTotal*(1-percent))),ilTotal=state.province?6500+((Math.max(0,PROVINCES.indexOf(state.province))*7919)%19000):0;if(['İstanbul','Ankara','İzmir','Bursa','Antalya','Konya','Adana','Gaziantep'].includes(state.province))ilTotal*=3;return{tr,il:ilTotal?Math.max(1,Math.round(ilTotal*(1-percent))):null,trTotal,ilTotal}}
function weakest(){let rows=Object.entries(state.bySubject).filter(([,v])=>v.a>0).map(([name,v])=>({name,acc:Math.round(v.c/v.a*100),a:v.a}));return rows.sort((x,y)=>x.acc-y.acc||y.a-x.a)[0]||null}
function updateUI(){let acc=state.answered?Math.round(state.correct/state.answered*100):null,r=rankModel(),w=weakest();document.getElementById('daily').textContent=`${Math.min(state.answered,30)} / 30`;document.getElementById('accuracy').textContent=acc===null?'—':`%${acc}`;document.getElementById('points').textContent=state.points;document.getElementById('trRank').textContent=r.tr?`#${r.tr.toLocaleString('tr-TR')}`:'—';document.getElementById('trSub').textContent=r.tr?`${r.trTotal.toLocaleString('tr-TR')} demo katılımcısı içinde`:'Soru çözerek sıralamaya gir.';document.getElementById('ilRank').textContent=r.il?`#${r.il.toLocaleString('tr-TR')}`:'—';document.getElementById('plan').value=state.plan;document.getElementById('province').value=state.province;document.getElementById('coachHome').textContent=w?`Önceliğin ${w.name}. Bu dersteki doğruluğun %${w.acc}. Bir sonraki kısa turu burada yap.`:'İlk sorularını çöz. Zeus performansına göre öncelik vereceğin dersi belirleyecek.'}
function setPlan(v){state.plan=v;save()}function setProvince(v){state.province=v;save()}
function initLists(){let subjects=[...new Set(QUESTIONS.map(q=>q.subject))].sort();let grid=document.getElementById('subjectGrid'),sf=document.getElementById('subjectFilter'),ns=document.getElementById('noteSubject');grid.innerHTML=subjects.map(s=>`<button class="subject" onclick='startSubject(${JSON.stringify(s)})'><span>${ICONS[s]||'◆'}</span>${s}</button>`).join('');subjects.forEach(s=>{let a=document.createElement('option');a.value=s;a.textContent=s;sf.appendChild(a);let b=a.cloneNode(true);ns.appendChild(b)});PROVINCES.forEach(p=>{let o=document.createElement('option');o.value=p;o.textContent=p;document.getElementById('province').appendChild(o)})}
function buildPool(pool,count){let seen=new Set(state.seen),fresh=shuffle(pool.filter(q=>!seen.has(q.id))),old=shuffle(pool.filter(q=>seen.has(q.id))),all=[...fresh,...old];return all.slice(0,Math.min(count,all.length))}
function startFull(){session=buildPool(QUESTIONS,30);startSession('30 Soruluk Arena')}
function startSubject(s){let pool=QUESTIONS.filter(q=>q.subject===s);session=buildPool(pool,pool.length);startSession(`${s} Arenası`)}
function startFiltered(){let e=document.getElementById('examFilter').value,s=document.getElementById('subjectFilter').value,d=document.getElementById('difficultyFilter').value,pool=QUESTIONS.filter(q=>(e==='ALL'||q.exam===e)&&(s==='ALL'||q.subject===s)&&(d==='ALL'||q.difficulty===d));if(!pool.length){alert('Bu filtrede demo sorusu yok.');return}session=buildPool(pool,pool.length);startSession('Hızlı Arena')}
function startSession(title){responses=[];idx=0;locked=false;document.getElementById('quizTitle').textContent=title;renderQuestion();go('quiz')}
function renderQuestion(){let q=session[idx];document.getElementById('feedback').classList.remove('show');document.getElementById('nextBtn').disabled=true;locked=false;if(!q){document.getElementById('qText').textContent='Dersler sekmesinden veya ana sayfadan bir tur başlat.';document.getElementById('options').innerHTML='';return}document.getElementById('quizCount').textContent=`${idx+1} / ${session.length}`;document.getElementById('quizProgress').style.width=`${idx/session.length*100}%`;document.getElementById('qExam').textContent=`${q.exam} • ${q.subject} • ${q.difficulty}`;document.getElementById('qTopic').textContent=q.topic;document.getElementById('qText').textContent=q.q;document.getElementById('options').innerHTML=q.o.map((o,i)=>`<button class="option" onclick="answer(${i},this)"><span class="letter">${'ABCDE'[i]}</span><span>${o}</span></button>`).join('')}
function answer(choice,btn){if(locked)return;locked=true;let q=session[idx],ok=choice===q.a;btn.classList.add('selected');document.querySelectorAll('.option').forEach(x=>x.disabled=true);responses.push({q,choice});state.answered++;if(ok){state.correct++;state.points+=10}let st=state.bySubject[q.subject]||(state.bySubject[q.subject]={a:0,c:0});st.a++;if(ok)st.c++;if(!state.seen.includes(q.id))state.seen.push(q.id);document.getElementById('feedback').classList.add('show');document.getElementById('nextBtn').disabled=false;document.getElementById('nextBtn').textContent=idx===session.length-1?'TURU TAMAMLA':'SONRAKİ SORU';save()}
function nextQuestion(){if(!locked)return;if(idx>=session.length-1){finishQuiz();return}idx++;renderQuestion()}
function finishQuiz(){if(!responses.length){go('reports');return}if(state.plan==='premium'){revealResults();return}let ad=document.getElementById('ad'),btn=document.getElementById('adBtn'),count=document.getElementById('adCount'),s=3;ad.classList.add('show');btn.disabled=true;count.textContent='3 saniye';let t=setInterval(()=>{s--;if(s<=0){clearInterval(t);count.textContent='Reklam tamamlandı';btn.disabled=false}else count.textContent=`${s} saniye`},1000)}
function revealResults(){document.getElementById('ad').classList.remove('show');renderReports(true);go('reports')}
function renderReports(unlock=false){let acc=state.answered?Math.round(state.correct/state.answered*100):0,r=rankModel();document.getElementById('reportPlan').textContent=state.plan==='premium'?'PREMIUM • REKLAMSIZ':'ÜCRETSİZ';document.getElementById('reportAccuracy').textContent=`%${acc}`;document.getElementById('reportLine').textContent=state.answered?`${state.answered} soru • ${state.correct} doğru • ${state.points} puan`:'Henüz soru çözmedin.';document.getElementById('reportRanks').textContent=`TR ${r.tr?'#'+r.tr.toLocaleString('tr-TR'):'—'}`;document.getElementById('reportProvince').textContent=state.province?(r.il?`${state.province} #${r.il.toLocaleString('tr-TR')}`:state.province):'İl seçilmedi';let box=document.getElementById('review');if(!unlock&&box.dataset.unlocked!=='1'){box.innerHTML='<div class="small">Tur tamamlandığında cevapların burada gösterilir.</div>';return}box.dataset.unlocked='1';box.innerHTML=responses.length?responses.map((r,i)=>`<div class="review-item"><b>${i+1}. ${r.q.subject}</b> <b class="${r.choice===r.q.a?'ok':'bad'}">${r.choice===r.q.a?'DOĞRU':'YANLIŞ'}</b><br>${r.q.q}<br><span class="small">Senin cevabın: ${'ABCDE'[r.choice]}) ${r.q.o[r.choice]}</span><br><span class="gold">Doğru cevap: ${'ABCDE'[r.q.a]}) ${r.q.o[r.q.a]}</span><br><span class="small">Çözüm: ${r.q.e}</span></div>`).join(''):'<div class="small">Bu turda kayıtlı cevap yok.</div>'}
function setNoteExam(v,btn){noteExam=v;document.querySelectorAll('[data-noteexam]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderNotes()}
function renderNotes(){let s=document.getElementById('noteSubject').value,rows=NOTES.filter(n=>(noteExam==='ALL'||n.exam===noteExam)&&(s==='ALL'||n.subject===s));document.getElementById('notesGrid').innerHTML=rows.map(n=>`<div class="note"><div class="small gold">${n.exam} • ${n.subject}</div><h3>${n.title}</h3><p><strong>⚠ Dikkat:</strong> ${n.d}</p><p><strong>🧠 Kavram:</strong> ${n.k}</p><p><strong>💡 Örnek:</strong> ${n.x}</p></div>`).join('')}
function renderCoach(){let w=weakest(),acc=state.answered?Math.round(state.correct/state.answered*100):0;document.getElementById('oracleTitle').textContent=!w?'Arenaya Hoş Geldin':w.acc<60?'Önce Açığı Kapat':'Ritmi Koru';document.getElementById('oracleText').textContent=!w?'Soru çözdükçe çalışma önceliklerin burada görünecek.':`Genel doğruluğun %${acc}. En düşük alanın ${w.name} (%${w.acc}). Önce kısa odak turu, sonra karışık sorular.`;let tips=[w?`⚡ Öncelik: ${w.name}`:'⚡ İlk hedef: 10 karışık soru',state.answered<30?`🎯 Günlük hedefe ${30-Math.min(state.answered,30)} soru kaldı.`:'🎯 Günlük hedef tamamlandı.',acc>=80&&state.answered>=5?'🏆 Doğruluk güçlü; hız çalışmasını artır.':'⏳ Önce doğruluk, sonra hız.','🧠 Yanlış soruda çözüm mantığını öğren.'];document.getElementById('tips').innerHTML=tips.map(x=>`<div class="tip">${x}</div>`).join('')}
function init(){initLists();renderNotes();timers();setInterval(timers,1000);updateUI();renderCoach();renderReports();renderQuestion()}init();